[build-system]

requires = ["setuptools>= 61.0"]

build-backend = "setuptools.build_meta"
[project]
name = "test_package"
version = "0.1.0"
description = "simple python packe to add two numbers for testing purpose" 

author = "Ashutosh raj"
README = "README.md"
requires-python = ">=3.8"
licence = "MIT"
